dataset: cifar10
data_path: data/cifar10
trigger_type: checkerboard
trigger_label: single
new_label: 9
trigger_size: 100
finetune_size: 0.3

model: ResNet18
phase: 2_finetune
visualize: False
#新增字段：指定初始训练模型的完整路径
init_ckpt_path: checkpoints/adi_init/adi_checkerboard_resnet_cifar10.pth
save_dir: checkpoints/adi_ft
save_name: adi_ft_checkerboard_resnet_cifar10.pth
exp_name: adi_ft_checkerboard_resnet_cifar10
ckpt_suffix: smalllr
method: adi
batchsize: 256
batchsize_wm: 64
batchsize_c: 64
optimizer: [adam, adam, adam]
lr: [1e-4, 1e-4, 1e-4]
wd: [1e-4, 1e-4, 1e-4]
scheduler: [cosine, na, na]
scheduler_step: [20, 10, 10]
scheduler_gamma: [0.5, 0.5, 0.5]
lr_min: [1e-5,0,0]
epochs: [200, 50, 30]
x: "-60:10:10"
y: "-15:15:10"
vmin: 0.0
vmax: 1
vlevel: 0.05
n_ckpt_skips: 25
eval_robust: False
log_wandb: True
seed: 20